version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:11.6
    privileged: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    networks:
      - bridge
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    privileged: true
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - bridge
  # cli:
  #   image: nestjs/cli
  #   working_dir: /workspace
  #   volumes:
  #     - .:/workspace
  #   tty: true
  # node:
  #   image: node:${NODE_VERSION}
  #   working_dir: /workspace
  #   ports:
  #     - ${APP_PORT}:3000
  #   expose:
  #     - '3000'
  #   networks:
  #     - bridge
  #   # command: apk add build-base python gcc g++
  #   tty: true
networks:
  bridge:
    driver: bridge
